use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let package_version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "unknown".into());
    let commit =
        git_output(["rev-parse", "--short=12", "HEAD"]).unwrap_or_else(|| "unknown".into());
    let dirty = git_dirty();
    let dirty_suffix = if dirty { "-dirty" } else { "" };

    println!("cargo:rustc-env=CPTOOL_VERSION={package_version} (commit {commit}{dirty_suffix})");

    emit_builtin_checkers();
    emit_git_rerun_hints();
}

fn emit_builtin_checkers() {
    let checker_dir = Path::new("example")
        .join("assets")
        .join("testlib")
        .join("checkers");
    println!("cargo:rerun-if-changed={}", checker_dir.display());

    let mut entries = std::fs::read_dir(&checker_dir)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", checker_dir.display()))
        .map(|entry| entry.unwrap_or_else(|err| panic!("failed to read checker dir entry: {err}")))
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("cpp"))
        .collect::<Vec<_>>();
    entries.sort();

    let mut generated = String::from(
        "// @generated by build.rs; do not edit by hand.\n\
         pub static BUILTIN_CHECKERS: &[(&str, &str, &str)] = &[\n",
    );
    for path in entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let filename = path
            .file_name()
            .and_then(|value| value.to_str())
            .unwrap_or_else(|| panic!("checker filename is not valid UTF-8: {}", path.display()));
        let id = path
            .file_stem()
            .and_then(|value| value.to_str())
            .unwrap_or_else(|| panic!("checker stem is not valid UTF-8: {}", path.display()));
        let source = std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
        generated.push_str(&format!("    ({id:?}, {filename:?}, {source:?}),\n"));
    }
    generated.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by Cargo");
    std::fs::write(
        PathBuf::from(out_dir).join("builtin_checkers.rs"),
        generated,
    )
    .expect("failed to write generated builtin checker registry");
}

fn git_output<const N: usize>(args: [&str; N]) -> Option<String> {
    let output = Command::new("git").args(args).output().ok()?;
    if !output.status.success() {
        return None;
    }
    let text = String::from_utf8(output.stdout).ok()?;
    let text = text.trim();
    (!text.is_empty()).then(|| text.to_string())
}

fn git_dirty() -> bool {
    git_status(["diff", "--quiet", "--ignore-submodules", "--"]).is_some_and(|clean| !clean)
        || git_status(["diff", "--cached", "--quiet", "--ignore-submodules", "--"])
            .is_some_and(|clean| !clean)
}

fn git_status<const N: usize>(args: [&str; N]) -> Option<bool> {
    let status = Command::new("git").args(args).status().ok()?;
    Some(status.success())
}

fn emit_git_rerun_hints() {
    println!("cargo:rerun-if-changed=Cargo.toml");

    let Some(git_dir) = git_dir() else {
        return;
    };
    println!("cargo:rerun-if-changed={}", git_dir.join("HEAD").display());
    println!("cargo:rerun-if-changed={}", git_dir.join("index").display());

    let Ok(head) = std::fs::read_to_string(git_dir.join("HEAD")) else {
        return;
    };
    let Some(ref_name) = head.trim().strip_prefix("ref: ") else {
        return;
    };
    println!(
        "cargo:rerun-if-changed={}",
        git_dir.join(ref_name).display()
    );
}

fn git_dir() -> Option<PathBuf> {
    let path = Path::new(".git");
    if path.is_dir() {
        return Some(path.to_path_buf());
    }

    let content = std::fs::read_to_string(path).ok()?;
    let gitdir = content.trim().strip_prefix("gitdir: ")?;
    Some(PathBuf::from(gitdir))
}
